version: '3.8'
services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
      - 8001:5000
    volumes: 
      - .:/app
    depends_on: 
      - db
  
  db:
    image: mysql
    restart: always 
    environment:
      MYSQL_DATABASE: main
      MYSQL_PASSWORD: root 
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - .dbdata:/var/lib/mysql 
    ports:  # just to check data, not required in prod
      - 33067:3306 